# Generated by Django 5.0.1 on 2024-01-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Roomnumber')),
                ('AmountMembers', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Amount of Members')),
                ('StopCount', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Amount of Stop')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Amount of Votes')),
                ('Raum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_voting.raum')),
            ],
        ),
    ]
