# Generated by Django 5.0.1 on 2024-01-31 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0003_alter_film_raum'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='filmName',
            field=models.CharField(max_length=100, null=True, verbose_name='Filmname'),
        ),
        migrations.AlterField(
            model_name='film',
            name='Raum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_voting.raum'),
        ),
    ]
