# Generated by Django 5.0.1 on 2024-01-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0004_film_filmname_alter_film_raum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Raum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_voting.raum'),
        ),
    ]
