# Generated by Django 5.0.1 on 2024-02-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0006_alter_film_raum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raum',
            name='Number',
            field=models.CharField(max_length=100, null=True, verbose_name='Roomnumber'),
        ),
    ]
