# Generated by Django 5.0.1 on 2024-02-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0007_alter_raum_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='votes',
            field=models.IntegerField(verbose_name='Amount of Votes'),
        ),
        migrations.AlterField(
            model_name='raum',
            name='AmountMembers',
            field=models.IntegerField(verbose_name='Amount of Members'),
        ),
        migrations.AlterField(
            model_name='raum',
            name='StopCount',
            field=models.IntegerField(verbose_name='Amount of Stop'),
        ),
    ]
