# Generated by Django 5.0.1 on 2024-02-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0008_alter_film_votes_alter_raum_amountmembers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raum',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
