# Generated by Django 5.0.1 on 2024-02-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0009_alter_raum_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raum',
            name='Number',
        ),
        migrations.AddField(
            model_name='film',
            name='movieApiID',
            field=models.IntegerField(default=1, verbose_name='movieApiID'),
            preserve_default=False,
        ),
    ]
