# Generated by Django 5.0.1 on 2024-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0011_raum_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raum',
            name='Genre',
        ),
        migrations.AddField(
            model_name='raum',
            name='Genre_ID',
            field=models.IntegerField(default=0, verbose_name='Genre_ID'),
            preserve_default=False,
        ),
    ]
