# Generated by Django 5.0.1 on 2024-03-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0012_remove_raum_genre_raum_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
    ]
