# Generated by Django 5.0.1 on 2024-03-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0014_alter_film_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.CharField(max_length=1000, null=True, verbose_name='Image'),
        ),
    ]
