# Generated by Django 5.0.1 on 2024-03-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0015_film_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='forAdult',
            field=models.BooleanField(default=1, verbose_name='For Adult'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.JSONField(default=list, verbose_name='Genres'),
        ),
        migrations.AddField(
            model_name='film',
            name='voteAverage',
            field=models.FloatField(default=0, verbose_name='Vote Average'),
            preserve_default=False,
        ),
    ]
