# Generated by Django 5.0.1 on 2024-04-03 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0016_film_foradult_film_genres_film_voteaverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.CharField(max_length=100, null=True, verbose_name='brightness')),
                ('background', models.CharField(max_length=100, null=True, verbose_name='background')),
                ('onBackground', models.CharField(max_length=100, null=True, verbose_name='onBackground')),
                ('primary', models.CharField(max_length=100, null=True, verbose_name='primary')),
                ('onPrimary', models.CharField(max_length=100, null=True, verbose_name='onPrimary')),
                ('secondary', models.CharField(max_length=100, null=True, verbose_name='secondary')),
                ('onSecondary', models.CharField(max_length=100, null=True, verbose_name='onSecondary')),
                ('surface', models.CharField(max_length=100, null=True, verbose_name='surface')),
                ('onSurface', models.CharField(max_length=100, null=True, verbose_name='onSurface')),
                ('error', models.CharField(max_length=100, null=True, verbose_name='error')),
                ('onError', models.CharField(max_length=100, null=True, verbose_name='onError')),
                ('Raum', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_voting.raum')),
            ],
        ),
    ]
