# Generated by Django 5.0.1 on 2024-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_voting', '0017_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
